# FIXME
C_INCLUDE_PATH=/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/libraries/:/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/cores/arduino:/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/variants/:/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/variants/eightanaloginputs/:/Users/jeff/Projects/arduino/libraries/ArduinoNunchuk

all:
	avr-g++ -I/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/libraries/ -I/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/cores/arduino -I/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/variants/ -I/Users/jeff/Projects/arduino/sdks/ArduinoCore-avr.git/variants/eightanaloginputs/ -I/Users/jeff/Projects/arduino/libraries/ArduinoNunchuk SNESwireless.cpp
